# SPDX-License-Identifier: Apache-2.0
"""Derive R0 limits for a dataset that has none (docs/adr/0007-r0-limits-from-nominal-envelope.md).

    python scripts/derive_limits.py configs/limits/opssat.derive.yaml     (or: make limits)

Per channel, fits the envelope of the samples labelled nominal in the training
window, then writes the limits file together with its provenance. The same data
and the same spec give the same file, byte for byte: nothing in it records when
or where it was generated.
"""

from __future__ import annotations

import argparse
import hashlib
from pathlib import Path

import yaml
from pydantic import BaseModel, ConfigDict, Field

from groundhog.detectors.r0_limits import AlarmPolicy, LimitsCheck, NoCheck, derive_limits
from groundhog.ingest.opssat import OpssatSource, nominal_values
from groundhog.replay.config import Window, load_config

RULE = (
    "min and max of the samples labelled nominal in the training window, "
    "each side pushed out by margin x (max - min)"
)


class DerivationSpec(BaseModel):
    """``configs/limits/<mission>.derive.yaml``: how a limits file is derived."""

    model_config = ConfigDict(frozen=True, extra="forbid")

    source: Path = Field(description="Replay configuration naming the data and channel kinds")
    training: Window
    margin: float = Field(ge=0, allow_inf_nan=False)
    defaults: AlarmPolicy
    output: Path


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__.split("\n\n")[0])
    parser.add_argument("spec", type=Path, help="e.g. configs/limits/opssat.derive.yaml")
    parser.add_argument(
        "--check",
        action="store_true",
        help="write nothing; fail unless the limits file is exactly what the spec derives",
    )
    args = parser.parse_args(argv)

    raw = args.spec.read_bytes()
    spec = DerivationSpec.model_validate(yaml.safe_load(raw))
    source = load_config(spec.source).source
    data = OpssatSource(source)  # checks the declared channels against the data
    nominal = nominal_values(source.path, spec.training.start, spec.training.end)

    limits = derive_limits(
        mission=source.mission,
        kinds={name: channel.kind for name, channel in source.channels.items()},
        nominal=nominal,
        margin=spec.margin,
        defaults=spec.defaults,
        provenance={
            "generator": "scripts/derive_limits.py",
            "spec": args.spec.as_posix(),
            "spec_sha256": hashlib.sha256(raw).hexdigest(),
            "data_md5": data.describe()["md5"],
            "training": spec.training.model_dump(mode="json"),
            "rule": RULE,
            "margin": spec.margin,
            "nominal_samples": {
                name: len(nominal.get(name, [])) for name in sorted(source.channels)
            },
        },
    )
    body = yaml.safe_dump(
        limits.model_dump(mode="json", exclude_unset=True), sort_keys=False, default_flow_style=None
    )
    header = (
        f"# Generated by scripts/derive_limits.py from {args.spec.as_posix()}.\n"
        "# Do not edit by hand: change the spec and run `make limits`.\n"
    )
    if args.check:
        current = spec.output.read_text(encoding="utf-8") if spec.output.exists() else None
        if current != header + body:
            print(
                f"{spec.output.as_posix()} is not what {args.spec.as_posix()} derives: make limits"
            )
            return 1
        print(f"{spec.output.as_posix()} is up to date")
        return 0
    spec.output.write_text(header + body, encoding="utf-8", newline="\n")

    checks = list(limits.channels.values())
    print(
        f"wrote {spec.output.as_posix()}: {len(checks)} channels, "
        f"{sum(isinstance(c, LimitsCheck) for c in checks)} with limits, "
        f"{sum(isinstance(c, NoCheck) for c in checks)} unchecked"
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
